dist: xenial
sudo: required
language: python
cache:
  pip: true
  directories:
    - "frontend/node_modules"
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
install:
  - pip -q install tox tox-travis
  - cd frontend
  - npm install
  - cd $TRAVIS_BUILD_DIR
script:
  - cd frontend
  - npm run lint
  - npm run build
  - cd $TRAVIS_BUILD_DIR
  - tox
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.9"
notifications:
  email: false
